version: '3.8'

services:
  app:
    build: .
    container_name: projeto-vm-app
    environment:
      - PROJECT_NAME=projeto-vm
      - ENVIRONMENT=dev
      - INSTANCE_ID=local
      - REGION=local
    ports:
      - "3000:3000"
    restart: unless-stopped 