# ============================================================================
# ServiceAccount, Role e RoleBinding para o Velero
# A ServiceAccount permite que o Velero interaja com o cluster Kubernetes.
# A Role define permissões necessárias para backup/restore.
# O RoleBinding vincula a Role à ServiceAccount.
# ============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: velero
  name: velero
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "persistentvolumeclaims", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero
  namespace: velero
subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
roleRef:
  kind: Role
  name: velero
  apiGroup: rbac.authorization.k8s.io 