# ============================================================================
# Deployment do Velero
# Este deployment instala o Velero no cluster, usando a ServiceAccount criada.
# O Velero será configurado para usar o plugin AWS e salvar backups no S3.
# O secret de credenciais AWS deve ser criado separadamente.
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
    spec:
      serviceAccountName: velero  # Usa a ServiceAccount dedicada
      containers:
        - name: velero
          image: velero/velero:v1.13.0
          command:
            - /velero
          args:
            - server
          env:
            # Configurações do S3 e região AWS
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_BUCKET
              value: projeto-vm-velero-backup
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
            - name: cloud-credentials
              mountPath: /credentials
              readOnly: true
      volumes:
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials  # Secret com as credenciais AWS 